spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client_score
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_null
  flyway:
    enabled: true
