spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client_score
    username: postgres
    password: postgres
